// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAd9F35Tz-ZNhCekCV4WCpKOLM-46ydAYo',
    appId: '1:1043017566961:web:a808c87ae4e5ab868eb750',
    messagingSenderId: '1043017566961',
    projectId: 'made-gslc-2',
    authDomain: 'made-gslc-2.firebaseapp.com',
    storageBucket: 'made-gslc-2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGqdwou9ly0qGvQae1rdm6uUnl2nuQTkc',
    appId: '1:1043017566961:android:f3f5ded9d16098c58eb750',
    messagingSenderId: '1043017566961',
    projectId: 'made-gslc-2',
    storageBucket: 'made-gslc-2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4rFT0KsRIkQP_XdnS6v510ARpAEAfz9w',
    appId: '1:1043017566961:ios:0a0da42631f131988eb750',
    messagingSenderId: '1043017566961',
    projectId: 'made-gslc-2',
    storageBucket: 'made-gslc-2.firebasestorage.app',
    iosBundleId: 'com.example.simpleAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4rFT0KsRIkQP_XdnS6v510ARpAEAfz9w',
    appId: '1:1043017566961:ios:0a0da42631f131988eb750',
    messagingSenderId: '1043017566961',
    projectId: 'made-gslc-2',
    storageBucket: 'made-gslc-2.firebasestorage.app',
    iosBundleId: 'com.example.simpleAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAd9F35Tz-ZNhCekCV4WCpKOLM-46ydAYo',
    appId: '1:1043017566961:web:6421ddeb05bafca18eb750',
    messagingSenderId: '1043017566961',
    projectId: 'made-gslc-2',
    authDomain: 'made-gslc-2.firebaseapp.com',
    storageBucket: 'made-gslc-2.firebasestorage.app',
  );
}
